### ISSUE TITLE
Error occurred compiling fairseq-py

### ISSUE THREAD

**Issue by fanqinan** [blcuicall/NLPCC_2018_TASK2_GEC#1]
An error occurred when I'm compiling fairseq-py. 

> fatal error: ATen/ATen.h: No such file or directory

I noticed that there is Aten.h in the source code of pytorch v0.2.0, but I cannot find it in the following path:

> $HOME/anaconda3/envs/[my_env]/lib/python3.6/site-packages/torch

I've compiled the pytorch according to https://github.com/pytorch/pytorch

Could you pls tell me if you have ever had such a problem? And how do you solve it?
Thank you very much.

**Comment by hongkairen** [comment]
Hi，this problem is due to your failure to compile the pytorch correctly.
You can follow the steps below to install:

export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]
# Install basic dependencies
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
conda install -c mingfeima mkldnn
# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 

git clone https://github.com/pytorch/pytorch.git
cd pytorch
git reset --hard a03e5cb40938b6b3f3e6dbddf9cff8afdff72d1b
git submodule update --init
pip install -r requirements.txt

python setup.py install

**Comment by yangzonglin1994** [comment]
Actually, use the latest version of PyTorch and fairseq library would be also ok. Then replace `generate.py` with `interactive.py` in `run.sh` and remove some flag not supported by `interactive.py`.
